# Generated by Django 3.0.6 on 2020-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_auto_20200530_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
